// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using VirtualRunner.Data;
using VirtualRunner.Data.Entities;

namespace VirtualRunner.Migrations
{
    [DbContext(typeof(VirtualRunnerDbContext))]
    partial class VirtualRunnerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("VirtualRunner.Data.Entities.Doacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<string>("Referencia");

                    b.Property<int?>("RegistroRunnerId");

                    b.Property<int>("SituacaoPagamento");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.HasIndex("RegistroRunnerId");

                    b.ToTable("Doacoes");
                });

            modelBuilder.Entity("VirtualRunner.Data.Entities.RegistroRunner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("GostaSerChamado");

                    b.Property<string>("NomeCompleto");

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.ToTable("RegistrosRunners");
                });

            modelBuilder.Entity("VirtualRunner.Data.Entities.Doacao", b =>
                {
                    b.HasOne("VirtualRunner.Data.Entities.RegistroRunner")
                        .WithMany("Doacoes")
                        .HasForeignKey("RegistroRunnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
